steps:
- name: 'gcr.io/cloud-builders/npm:latest'
  args: ['i', 'firebase-tools']
- name: 'gcr.io/cloud-builders/npm:latest'
  args: ['run', 'firebase:cideploy:funcs']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'